package src;

import java.util.HashMap;
import java.util.Map;

public class Gramatica {
    public static Map<String, Integer> TERMINAIS_E_NAO_TERMINAIS = new HashMap<String, Integer>();

    static {
        TERMINAIS_E_NAO_TERMINAIS.put("PROGRAM", 1);
        TERMINAIS_E_NAO_TERMINAIS.put("LABEL", 2);
        TERMINAIS_E_NAO_TERMINAIS.put("CONST", 3);
        TERMINAIS_E_NAO_TERMINAIS.put("VAR", 4);
        TERMINAIS_E_NAO_TERMINAIS.put("PROCEDURE", 5);
        TERMINAIS_E_NAO_TERMINAIS.put("BEGIN", 6);
        TERMINAIS_E_NAO_TERMINAIS.put("END", 7);
        TERMINAIS_E_NAO_TERMINAIS.put("INTEGER", 8);
        TERMINAIS_E_NAO_TERMINAIS.put("ARRAY", 9);
        TERMINAIS_E_NAO_TERMINAIS.put("OF", 10);
        TERMINAIS_E_NAO_TERMINAIS.put("CALL", 11);
        TERMINAIS_E_NAO_TERMINAIS.put("GOTO", 12);
        TERMINAIS_E_NAO_TERMINAIS.put("IF", 13);
        TERMINAIS_E_NAO_TERMINAIS.put("THEN", 14);
        TERMINAIS_E_NAO_TERMINAIS.put("ELSE", 15);
        TERMINAIS_E_NAO_TERMINAIS.put("WHILE", 16);
        TERMINAIS_E_NAO_TERMINAIS.put("DO", 17);
        TERMINAIS_E_NAO_TERMINAIS.put("REPEAT", 18);
        TERMINAIS_E_NAO_TERMINAIS.put("UNTIL", 19);
        TERMINAIS_E_NAO_TERMINAIS.put("READLN", 20);
        TERMINAIS_E_NAO_TERMINAIS.put("WRITELN", 21);
        TERMINAIS_E_NAO_TERMINAIS.put("OR", 22);
        TERMINAIS_E_NAO_TERMINAIS.put("AND", 23);
        TERMINAIS_E_NAO_TERMINAIS.put("NOT", 24);
        TERMINAIS_E_NAO_TERMINAIS.put("IDENTIFICADOR", 25);
        TERMINAIS_E_NAO_TERMINAIS.put("INTEIRO", 26);
        TERMINAIS_E_NAO_TERMINAIS.put("FOR", 27);
        TERMINAIS_E_NAO_TERMINAIS.put("TO", 28);
        TERMINAIS_E_NAO_TERMINAIS.put("CASE", 29);
        TERMINAIS_E_NAO_TERMINAIS.put("+", 30);
        TERMINAIS_E_NAO_TERMINAIS.put("-", 31);
        TERMINAIS_E_NAO_TERMINAIS.put("*", 32);
        TERMINAIS_E_NAO_TERMINAIS.put("/", 33);
        TERMINAIS_E_NAO_TERMINAIS.put("[", 34);
        TERMINAIS_E_NAO_TERMINAIS.put("]", 35);
        TERMINAIS_E_NAO_TERMINAIS.put("(", 36);
        TERMINAIS_E_NAO_TERMINAIS.put(")", 37);
        TERMINAIS_E_NAO_TERMINAIS.put(":=", 38);
        TERMINAIS_E_NAO_TERMINAIS.put(":", 39);
        TERMINAIS_E_NAO_TERMINAIS.put("=", 40);
        TERMINAIS_E_NAO_TERMINAIS.put(">", 41);
        TERMINAIS_E_NAO_TERMINAIS.put(">=", 42);
        TERMINAIS_E_NAO_TERMINAIS.put("<", 43);
        TERMINAIS_E_NAO_TERMINAIS.put("<=", 44);
        TERMINAIS_E_NAO_TERMINAIS.put("<>", 45);
        TERMINAIS_E_NAO_TERMINAIS.put(",", 46);
        TERMINAIS_E_NAO_TERMINAIS.put(";", 47);
        TERMINAIS_E_NAO_TERMINAIS.put("LITERAL", 48);
        TERMINAIS_E_NAO_TERMINAIS.put(".", 49);
        TERMINAIS_E_NAO_TERMINAIS.put("..", 50);
        TERMINAIS_E_NAO_TERMINAIS.put("$", 51);
    }
}
